### ISSUE TITLE
train_nav.py goes into Pdb.set_trace()

### ISSUE THREAD

**Issue by satyenrajpal** [facebookresearch/EmbodiedQA#11]
During training of train_nav.py, pdb.set_trace() is called in data.py. Specifically, in [this part](https://github.com/facebookresearch/EmbodiedQA/blob/e1ec2be048ab5e255923ba1e6c577eb78ca72e44/training/data.py#L426-L433l). I'm unable to grasp why exactly `len` function is failing, Do you have a fix for that?

**Comment by LisaAnne** [comment]
So this is wrong: 

"while (counter <= self.max_controller_actions) and (backtrack_controller_steps[counter] == backtrack_controller_steps[0]) and (counter <= len(backtrack_controller_steps)):"

It should be: 

"while (counter <= self.max_controller_actions) and (counter < len(backtrack_controller_steps) and (backtrack_controller_steps[counter] == backtrack_controller_steps[0]))"

See if that works for you.

**Comment by satyenrajpal** [comment]
Thanks! That worked. Closing this issue for now
