### ISSUE TITLE
Errors when running train_nav.py

### ISSUE THREAD

**Issue by yuanlixian** [facebookresearch/EmbodiedQA#15]
Hi I encountered some errors when training the navigator.

Sometimes it would show:
AssertionError: [Environment] House object not found! 
But when I cd into that house directory, there is a house.obj file.
The errors is caused by the the House3D/core.py, line 47, in local_create_house

And sometimes it would show:
python: vendor/csv.h:442: char * io::LineReader::next_line():
Assertion 'data_begin < data_end' failed

So where might be the problem of these errors?
Thanks

**Comment by abhshkdz** [comment]
Just confirming -- for the `AssertionError`, both `house.json` and `house.obj` are present, right? That is what the line checks for: [House3D/core.py#L32](https://github.com/abhshkdz/House3D/blob/master/House3D/core.py#L32).

For the latter, could you try pulling in the latest commits from my fork of [House3D](https://github.com/abhshkdz/house3d) and try again (specifically this commit: https://github.com/facebookresearch/House3D/commit/543c2d44ed971f3c6991818970020672c6505368#diff-8bac58e45cc8c294afc1b187a1387666).

**Comment by yuanlixian** [comment]
Thanks for the reply. 
For the first `AssertionError`, only `house.obj` is existed. Does it still require the `house.json` file when it's already converted?

And I'll try and pull the latest version of House3D that you provided and send you the feedback.

**Comment by abhshkdz** [comment]
> For the first AssertionError, only house.obj is existed. Does it still require the house.json file when it's already converted?

Yeah, it does need `house.json`: [House3D/house.py#L154](https://github.com/abhshkdz/House3D/blob/master/House3D/house.py#L154).

**Comment by yuanlixian** [comment]
Thanks for replying. It does run smoothly now.
