### ISSUE TITLE
suncg data unavailable

### ISSUE THREAD

**Issue by lixiangpengcs** [facebookresearch/EmbodiedQA#18]
The SUNCG data is unavailable now. Is there another way to get obj + mtl files for the houses in EQA?

**Comment by abhshkdz** [comment]
Hi @lixiangpengcs, the only way to access SUNCG was through their website. And with that down, unfortunately, we don’t have a way to get these files, sorry.

**Comment by lixiangpengcs** [comment]
Thank you for your reply. @abhshkdz I will sent email to SUNCG official and ask help for them.

**Comment by akshay-sharma1995** [comment]
Hey @lixiangpengcs did you figure out how to get the SUNCG dataset?

**Comment by lixiangpengcs** [comment]
hey @akshay-sharma1995 , I didn't get any apply from SUNCG official site.

**Comment by akshay-sharma1995** [comment]
Ok, thanks for the update.

**Comment by jiunyen-ching** [comment]
Is the dataset along with the toolkit permanently taken down? Any updates so far?

**Comment by rohitmenon86** [comment]
Is there a way to use another dataset for e.g. the Matterport 3D dataset, if I want to train the agent in a different environment for different tasks?

**Comment by abhshkdz** [comment]
Yeah, check out [HM3D](https://aihabitat.org/datasets/hm3d/) and [HM3D-Semantics](https://aihabitat.org/datasets/hm3d-semantics/)!

**Comment by Ukias** [comment]
Which parts of the EQA framework have to be changed in order to use the HM3D or the HM3D-Semantics datasets? My goal is to use an arm with a fixed base in a single room to answer simple questions like "How many objects are on the table?".
