### ISSUE TITLE
Out of memory in train_vqa.py with 8 num_processes

### ISSUE THREAD

**Issue by ZhuFengdaaa** [facebookresearch/EmbodiedQA#6]
I have a linux server with 93G physical memory and 64G swap, but it still got the error below when I set `num_processes=8`: 
```
File "/home/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 73, in _launch 
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
````
---
Update: I found that the problem is it needs 65G Memory for each process in data loader. And the data in data loader is not shared. The implementation is consistent of [multiprocessing](https://pytorch.org/docs/stable/notes/multiprocessing.html). Since A3C need threads to get a better performance, I'm wondering if there is some way to have more `num_processes` by sharing data in data loader between processes?

![train log](https://cdn.pbrd.co/images/HAX41Fq.jpg) 
X-axes is number of epoch. This is the log I test on validation set every training epoch. My train log shows that the training process of train_vqa.py is not so stable. Is it similar to yours ?

**Comment by eugenium** [comment]
Were you able to resolve this? I found the same issue... it seems the vqa training diverges for me when running the default settings in this code.

**Comment by abhshkdz** [comment]
Please pull the latest source from the repository, and the same command should work.
