### ISSUE TITLE
The version of SUNCG dataset v1, v2 or v2.1

### ISSUE THREAD

**Issue by gengmujian10** [facebookresearch/EmbodiedQA#8]
I download the suncg v2.1 dataset, and do "python make_houses.py"
We only get 742 house.obj file while the eqa_v1.json reports a total envs of 770.
This cause the error during our training and evalution.
Error Code:
house objects not found! objFile=</EmbodiedQA/data/suncg/house/8675a21d3eb31d8c69e85a945ceeec00/house.obj>

I am sure the house path is correct. Is this problem relevant to the version suncg dataset ?

**Comment by abhshkdz** [comment]
Thanks for pointing this out. Yes, this is a suncg version issue.

EQA v1 relies on suncg v1 (and doesn't work with v2+ due to minor differences). I've added a note in the readme.
